### ISSUE TITLE
Adding Custom fields to Work Items

### ISSUE THREAD

**Issue by cwoolum** [microsoft/vsts-extension-samples#31]
Is it possible to add custom fields to work items as part of the a VSTS extension? I'd like to add some custom input fields and then save those into custom fields on the work item. I'd like this to be automated as part of the extension install instead of the user having to customize their Work Items manually.

**Comment by defu** [comment]
We're working on REST APIs that will allow users to customize their VSTS processes. This includes adding custom work item types, states, and fields. We are targeting late this year to ship these APIs.

**Comment by phavanagi** [comment]
Hi @defu ,

Do we have the api's that wil allow me to add the custom fields to VSTS?
