### ISSUE TITLE
Dependencies loaded from the wrong path

### ISSUE THREAD

**Issue by petritzdesigns** [Microsoft/vsts-extension-samples#70]
I checked out the ui-fabric-react folder and wanted to test the extension locally. Therefore I installed the npm-package "http-server" und ran the `gulp --local` command.

The upload and packaging both worked fine. BUT when the hub is loaded from the web interface it cannot find some important dependencies for ui-fabric because it looks for them in the root directory. However, it is working when using the `gulp` command and bundle everything together.

Also I could not provide a quickfix and copy the needed files in the root directory, as I could not find the files in the node_modules folder. Is there anything else I have to consider? Thanks.

**Comment by petritzdesigns** [comment]
![image](https://user-images.githubusercontent.com/7904630/29563681-f8113b84-873e-11e7-9d73-1fecb496d91b.png)

**Comment by serkan-inci** [comment]
Hi @petritzdesigns 

This issue should be fixed with below PR:

https://github.com/Microsoft/vsts-extension-samples/pull/71
